import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import { poppins } from "./ui/fonts";


export const metadata: Metadata = {
  title: "WayUp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
